### ISSUE TITLE
Strange permissions

### ISSUE THREAD

**Issue by billy34** [speedball2001/nompsort-mx#2]
Hello
When installing 2.0beta1 on thunderbird 78.2.2 it asks full and illimited access to thunderbird and computer. Is this expected behavior ?
Thanks for this useful extension

**Comment by speedball2001** [comment]
This is the expected behaviour. 

In order to do what nompsort has to do it needs access Thunderbird's internals (in particular the table widget with the messages) using a so-called webextension experiment. Any addon that uses these experiments has complete access to everything inside Thunderbird where it potentially can do everything it wants. Which, btw, has always been the case with the legacy addons in Thunderbird 68 and earlier.
